package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "node_cc",
    deps = [
        "@gRPC//:gRPC",
        "@flatbuffers//:flatbuffers",
    ],
)

